### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by jakealistairwood** [nchomeldoe/portfolio#1]
Hey Natalie, hope everything is good with you and that you're enjoying your time on Oxna so far. Here's some feedback for your portfolio project:

What went well:
- Used a good attention-to-detail in getting the design to almost match that of the Figma wireframe
- BEM has been utilised really well and your HTML & SCSS is formatted and nested nicely.
- It's great to see that you're considering accessibility by adding aria-labels
- Fully responsive and you've used responsive units and variables throughout your code also

What could be better:
- I'm not sure if the blue icons work on the dark background - They need more contrast. Making them light blue could fix this?
- I'd make the images clickable for your projects also (opens up the hosted website in a new tab)

**Comment by nchomeldoe** [comment]
Morning, Jake! Thanks for your feedback! I am really enjoying it, it's nice
to be able to focus on it full time! I will make the images clickable as
you suggest. Which icons did you mean?
Thanks,
Nathalia
